### ISSUE TITLE
getClasses method in Application may need resource class

### ISSUE THREAD

**Issue by jmrossy** [mrj365/RestEasy-3.09-Spring-3.2.5-Swagger2.0#1]
Thanks for publishing this example. 

To get swagger 2 to work with RestEasy 3.0.9 for me, I had to add my resource class (in your example, PersonResource) to the resources list in the getClasses override.

I'm not sure how your version works without that. There must be something in your WEB-INF xml files that takes care of that for you.

**Comment by mrj365** [comment]
I believe it is line 21 in the RestApplication class that takes care of this for me.

`beanConfig.setResourcePackage("com.rest.resource");`
